service: ptt-beauty
entrypoint: python app.py
env: flex
runtime: python

runtime_config:
          python_version: 3

env_variables:
        SQLALCHEMY_DATABASE_URI: >-
                postgresql+psycopg2://postgres:123456@/ptt?host=/cloudsql/beuty-175714:asia-east1:beauty
        PTT_BOARD: 'beauty'
        PTT_PAGES: '2'
        PTT_CRAWLER_INTERVAL: '30'

beta_settings:
            cloud_sql_instances: beuty-175714:asia-east1:beauty

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

