entrypoint: python app.py
env: flex
runtime: python

runtime_config:
          python_version: 3

env_variables:
        SQLALCHEMY_DATABASE_URI: >-
                postgresql+psycopg2://postgres:123456@/beauty?host=/cloudsql/beuty-175714:asia-east1:beauty

beta_settings:
            cloud_sql_instances: beuty-175714:asia-east1:beauty
