service: default
entrypoint: python app.py
env: flex
runtime: python

runtime_config:
          python_version: 3

env_variables:
        SQLALCHEMY_DATABASE_URI: >-
                mysql+mysqlconnector://ptt:123456@/ptt?unix_socket=/cloudsql/ptt-crawler-176104:asia-northeast1:vpon-data-crawler
        PTT_BOARDS: 'gossiping beauty wanted movie car C_CHAT'
        PTT_PAGES: '5'
        PTT_CRAWLER_INTERVAL: '30'
        VISION_SERVER: 'https://vision-api-server-dot-ptt-crawler-176104.appspot.com/'

beta_settings:
        cloud_sql_instances: ptt-crawler-176104:asia-northeast1:vpon-data-crawler

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\..*$
        - bin/
        - __pycache__/
        - lib/
        - include/
        - pip-selfcheck.json
